name: Acquire activation file
on:
  workflow_dispatch: {}
jobs:
  activation:
    name: Request manual activation file 🔑
    runs-on: windows-latest
    steps:
      - name: Unity - Activate
        # You may pin to the exact commit or the version.
        # uses: game-ci/unity-activate@33cd3ea96f11f3a1ddcf8fa9d8d265d5ea81e240
        uses: game-ci/unity-activate@v2.0.0
        with:
          # Version of unity to use for building the project.
          unityVersion: 2021.3.16f1
